#!/bin/bash
 
PWD=`pwd`
ELASTICSEARCH_VERSION="1.4.3"
ELASTICSEARCH_PORT="9201"
 
curl -sS https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz | tar xz
cd elasticsearch-${ELASTICSEARCH_VERSION}
bin/plugin -install elasticsearch/elasticsearch-lang-mvel/${ELASTICSEARCH_VERSION}
 
echo "http.port: ${ELASTICSEARCH_PORT}" >> config/elasticsearch.yml
echo "script.disable_dynamic: false" >> config/elasticsearch.yml
 
bin/elasticsearch -d
sleep 5
 
cd PWD
