#!/bin/bash
 
BACK=`pwd`
export ELASTICSEARCH_VERSION="2.1.0"
export ELASTICSEARCH_PORT="9201"
export ELASTICSEARCH_URL="localhost:${ELASTICSEARCH_PORT}"
 
curl -sS https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz | tar xz
cd elasticsearch-${ELASTICSEARCH_VERSION}

echo "http.port: ${ELASTICSEARCH_PORT}" >> config/elasticsearch.yml
echo "script.inline: on" >> config/elasticsearch.yml
 
bin/elasticsearch -d
sleep 5
 
cd $BACK
