#!/bin/bash
 
BACK=`pwd`
export REDIS_VERSION="3.0.0"
export REDIS_PORT="6378"
export REDIS_URL="redis://localhost:${REDIS_PORT}"
 
wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz
tar xzf redis-${REDIS_VERSION}.tar.gz
cd redis-${REDIS_VERSION}
make 

echo "daemonize yes " >> redis.conf
src/redis-server redis.conf
sleep 3

cd $BACK